### ISSUE TITLE
Only receive the teams i'm managing - not all teams im administrating

### ISSUE THREAD

**Issue by forland** [Holdsport/holdsport-api#10]
Hi'

How come I only get the teams im managing and not also the ones I'm administrating?

Im connection to "https://api.holdsport.dk/v1/teams/"  with my personal username and password - and I am holdsport administrator in our club. I

**Comment by joerichsen** [comment]
Fixed in the latest release. And the fix has been deployed to our servers :-)

**Comment by forland** [comment]
Super cool - thanks..... - It works, Now I see all teams I'm admin on.

But I'm still not allowed to access the activities (- and probably other stuff) on teams i'm administrating. I would expect me to have access to the same data as I when I'm logged on to Holdsport.dk - as an administrator role?
