### ISSUE TITLE
POST requests don't work

### ISSUE THREAD

**Issue by nikijul** [Holdsport/holdsport-api#15]
Hello, I found this REST-API and was very delighted. I tried a few things and then unfortunately had to find out that this only works for GET-requests but not for POST-requests like adding a comment or changing a users status.
I only receive Response Cod: 500 Internal Server Error
Edit: I'm using SportMember

**Comment by joerichsen** [comment]
It's great to hear that you find the API useful 👍 

Posting comments or changing user status should work, though :-) 

I see the 500 error when you tried posting a new activity comment and it should be fixed now :-) Please try again.

Could you also try changing a user's status and write a new comment on this issue with the time that it failed? I can look into our logs and error tracking system and help debug/fix the issue.

**Comment by nikijul** [comment]
Posting Comments and creating rides now works for me. Thanks
But changing user status still throws an error
ErrorID: 200a14dd-832a-4037-80d8-26b07c20ad3c
Time: about 14:20 GMT+2

**Comment by joerichsen** [comment]
Sounds great :-)

I think that I have fixed the other error you saw with the user status now. 

Could you please try again and see if it works?

**Comment by nikijul** [comment]
Changing user status now works fine.
Thanks a lot
